import React, { useState } from "react";
import { Box, Text, useInput, useApp } from "ink";
import { StatusBar } from "../components/StatusBar.js";
import type { TestResults, StepResult } from "./TestingScreen.js";

interface ResultsScreenProps {
  results: TestResults;
}

export function ResultsScreen({
  results,
}: ResultsScreenProps): React.ReactElement {
  const { exit } = useApp();
  const [message, setMessage] = useState<string | null>(null);
  const [scrollOffset, setScrollOffset] = useState(0);

  const passed = results.steps.filter((s) => s.status === "pass").length;
  const failed = results.steps.filter((s) => s.status === "fail").length;
  const total = results.steps.length;

  const formatDuration = (ms: number): string => {
    if (ms < 1000) return `${ms}ms`;
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    }
    return `${seconds}s`;
  };

  const copyToClipboard = async (text: string): Promise<boolean> => {
    try {
      const { exec } = await import("node:child_process");
      const { promisify } = await import("node:util");
      const execAsync = promisify(exec);

      // Try xclip, xsel, pbcopy, or wl-copy depending on platform
      const platform = process.platform;
      let cmd: string;
      if (platform === "darwin") {
        cmd = "pbcopy";
      } else if (platform === "linux") {
        cmd = "xclip -selection clipboard";
      } else {
        cmd = "clip";
      }

      const child = execAsync(`echo ${JSON.stringify(text)} | ${cmd}`);
      await child;
      return true;
    } catch {
      return false;
    }
  };

  const formatMarkdownReport = (): string => {
    const lines: string[] = [];
    const icon = results.status === "pass" ? "PASS" : "FAIL";

    lines.push(`## Inspect Test Results: ${icon}`);
    lines.push("");
    lines.push(`**Instruction**: ${results.instruction}`);
    lines.push(`**Agent**: ${results.agent} | **Device**: ${results.device}`);
    lines.push(`**Duration**: ${formatDuration(results.totalDuration)} | **Tokens**: ${results.tokenCount}`);
    lines.push(`**Result**: ${passed}/${total} passed`);
    lines.push("");
    lines.push("| # | Step | Status |");
    lines.push("|---|------|--------|");

    for (const step of results.steps) {
      const statusIcon = step.status === "pass" ? "PASS" : "FAIL";
      lines.push(
        `| ${step.index + 1} | ${step.description} | ${statusIcon} |`
      );
      if (step.error) {
        lines.push(`| | Error: ${step.error} | |`);
      }
    }

    lines.push("");
    lines.push(`_Generated by [Inspect](https://github.com/inspect) at ${results.timestamp}_`);

    return lines.join("\n");
  };

  const saveFlow = async (): Promise<void> => {
    try {
      const { writeFileSync, existsSync, mkdirSync } = await import("node:fs");
      const { join } = await import("node:path");
      const flowsDir = join(process.cwd(), ".inspect", "flows");
      if (!existsSync(flowsDir)) {
        mkdirSync(flowsDir, { recursive: true });
      }
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const filename = `flow-${timestamp}.json`;
      const filepath = join(flowsDir, filename);

      const flow = {
        instruction: results.instruction,
        agent: results.agent,
        device: results.device,
        steps: results.steps.map((s) => ({
          description: s.description,
          assertion: s.assertion,
          toolCalls: s.toolCalls,
        })),
        createdAt: results.timestamp,
      };

      writeFileSync(filepath, JSON.stringify(flow, null, 2));
      setMessage(`Flow saved to ${filepath}`);
    } catch (err) {
      setMessage(`Failed to save flow: ${err}`);
    }
  };

  useInput(async (input, key) => {
    if (key.escape || (key.ctrl && input === "c") || input === "q") {
      exit();
      return;
    }

    // Scroll
    if (key.upArrow) {
      setScrollOffset((o) => Math.max(0, o - 1));
    }
    if (key.downArrow) {
      setScrollOffset((o) =>
        Math.min(results.steps.length - 1, o + 1)
      );
    }

    // Actions
    if (input === "y" || input === "Y") {
      const report = formatMarkdownReport();
      const copied = await copyToClipboard(report);
      setMessage(
        copied ? "Report copied to clipboard!" : "Copy failed — report printed to console"
      );
      if (!copied) {
        console.log(report);
      }
    }

    if (input === "p" || input === "P") {
      setMessage(
        "PR comment posting not yet connected — use 'inspect pr' with --comment flag"
      );
    }

    if (input === "s" || input === "S") {
      await saveFlow();
    }

    if (input === "r" || input === "R") {
      setMessage("Restart not yet implemented — run the command again");
    }
  });

  const visibleSteps = results.steps.slice(
    scrollOffset,
    scrollOffset + 12
  );

  return (
    <Box flexDirection="column" padding={1}>
      {/* Header */}
      <Box marginBottom={1} justifyContent="space-between">
        <Box>
          <Text bold color={results.status === "pass" ? "green" : "red"}>
            {results.status === "pass" ? "ALL TESTS PASSED" : "TESTS FAILED"}
          </Text>
        </Box>
        <Box>
          <Text dimColor>
            {formatDuration(results.totalDuration)} | {results.tokenCount}{" "}
            tokens
          </Text>
        </Box>
      </Box>

      {/* Summary */}
      <Box marginBottom={1} flexDirection="column">
        <Box>
          <Text dimColor>Instruction: </Text>
          <Text>{results.instruction}</Text>
        </Box>
        <Box>
          <Text dimColor>Agent: </Text>
          <Text>{results.agent}</Text>
          <Text dimColor> | Device: </Text>
          <Text>{results.device}</Text>
        </Box>
        <Box>
          <Text color="green">{passed} passed</Text>
          {failed > 0 && (
            <>
              <Text dimColor> | </Text>
              <Text color="red">{failed} failed</Text>
            </>
          )}
          <Text dimColor> | {total} total</Text>
        </Box>
      </Box>

      {/* Divider */}
      <Box>
        <Text dimColor>
          {"─".repeat(60)}
        </Text>
      </Box>

      {/* Step Results */}
      <Box flexDirection="column" marginTop={1}>
        {visibleSteps.map((step) => (
          <StepRow key={step.index} step={step} />
        ))}
      </Box>

      {results.steps.length > 12 && (
        <Box marginTop={1}>
          <Text dimColor>
            Showing {scrollOffset + 1}-
            {Math.min(scrollOffset + 12, results.steps.length)} of{" "}
            {results.steps.length} steps (up/down to scroll)
          </Text>
        </Box>
      )}

      {/* Message */}
      {message && (
        <Box marginTop={1}>
          <Text color="cyan">{message}</Text>
        </Box>
      )}

      {/* Actions */}
      <StatusBar
        items={[
          { label: "Y", value: "copy report" },
          { label: "P", value: "post to PR" },
          { label: "S", value: "save flow" },
          { label: "R", value: "restart" },
          { label: "Q/Esc", value: "quit" },
        ]}
      />
    </Box>
  );
}

function StepRow({ step }: { step: StepResult }): React.ReactElement {
  const statusIcon =
    step.status === "pass" ? (
      <Text color="green">✓</Text>
    ) : step.status === "fail" ? (
      <Text color="red">✗</Text>
    ) : (
      <Text dimColor>○</Text>
    );

  return (
    <Box flexDirection="column" marginLeft={1}>
      <Box>
        <Box width={3}>{statusIcon}</Box>
        <Box width={4}>
          <Text dimColor>{step.index + 1}.</Text>
        </Box>
        <Text
          color={
            step.status === "pass"
              ? "green"
              : step.status === "fail"
                ? "red"
                : undefined
          }
        >
          {step.description}
        </Text>
        {step.duration !== undefined && (
          <Text dimColor> ({step.duration}ms)</Text>
        )}
      </Box>
      {step.assertion && (
        <Box marginLeft={7}>
          <Text dimColor>Assert: {step.assertion}</Text>
        </Box>
      )}
      {step.error && (
        <Box marginLeft={7}>
          <Text color="red">Error: {step.error}</Text>
        </Box>
      )}
      {step.toolCalls && step.toolCalls.length > 0 && (
        <Box marginLeft={7} flexDirection="column">
          {step.toolCalls.map((call, i) => (
            <Text key={i} dimColor>
              Tool: {call.tool}({JSON.stringify(call.args)})
              {call.result ? ` → ${call.result}` : ""}
            </Text>
          ))}
        </Box>
      )}
    </Box>
  );
}
