import React, { useState } from "react";
import { Box, Text, useInput, useApp } from "ink";
import { TestPlanStep } from "@inspect/shared";
import { StatusBar } from "../components/StatusBar.js";
import { PALETTE, ICONS } from "../../utils/theme.js";
import { ProjectPaths } from "../../utils/project-context.js";

interface TestResults {
  instruction: string;
  status: "passed" | "failed";
  steps: TestPlanStep[];
  totalDuration: number;
  tokenCount: number;
  agent: string;
  device: string;
  timestamp: string;
}

interface ResultsScreenProps {
  results: TestResults;
}

export function ResultsScreen({ results }: ResultsScreenProps): React.ReactElement {
  const { exit } = useApp();
  const [message, setMessage] = useState<string | null>(null);
  const [scrollOffset, setScrollOffset] = useState(0);

  const passed = results.steps.filter((s) => s.status === "passed").length;
  const failed = results.steps.filter((s) => s.status === "failed").length;
  const total = results.steps.length;

  const formatDuration = (ms: number): string => {
    if (ms < 1000) return `${ms}ms`;
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    }
    return `${seconds}s`;
  };

  const copyToClipboard = async (text: string): Promise<boolean> => {
    try {
      const { execSync } = await import("node:child_process");
      execSync(`printf '%s' '${text.replace(/'/g, "'\"'\"'")}' | pbcopy`, {
        stdio: "pipe",
      });
      return true;
    } catch {
      return false;
    }
  };

  const formatMarkdownReport = (): string => {
    const lines: string[] = [];
    const icon = results.status === "passed" ? "PASS" : "FAIL";

    lines.push(`## Inspect Test Results: ${icon}`);
    lines.push("");
    lines.push(`**Instruction**: ${results.instruction}`);
    lines.push(`**Agent**: ${results.agent} | **Device**: ${results.device}`);
    lines.push(
      `**Duration**: ${formatDuration(results.totalDuration)} | **Tokens**: ${results.tokenCount}`,
    );
    lines.push(`**Result**: ${passed}/${total} passed`);
    lines.push("");
    lines.push("| # | Step | Status |");
    lines.push("|---|------|--------|");

    for (const [index, step] of results.steps.entries()) {
      const statusIcon = step.status === "passed" ? "PASS" : "FAIL";
      lines.push(`| ${index + 1} | ${step.instruction} | ${statusIcon} |`);
      if (step.error) {
        lines.push(`| | Error: ${step.error} | |`);
      }
    }

    lines.push("");
    lines.push(`_Generated by [Inspect](https://github.com/inspect) at ${results.timestamp}_`);

    return lines.join("\n");
  };

  const saveFlow = async (): Promise<void> => {
    try {
      const { writeFileSync, existsSync, mkdirSync } = await import("node:fs");
      const { join } = await import("node:path");
      const flowsDir = ProjectPaths.flows();
      if (!existsSync(flowsDir)) {
        mkdirSync(flowsDir, { recursive: true });
      }
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
      const filename = `flow-${timestamp}.json`;
      const filepath = join(flowsDir, filename);

      const flow = {
        instruction: results.instruction,
        agent: results.agent,
        device: results.device,
        steps: results.steps.map((s) => ({
          description: s.instruction,
          assertion: s.summary,
        })),
        createdAt: results.timestamp,
      };

      writeFileSync(filepath, JSON.stringify(flow, null, 2));
      setMessage(`Flow saved to ${filepath}`);
    } catch (err) {
      setMessage(`Failed to save flow: ${err}`);
    }
  };

  useInput(async (input, key) => {
    if (key.escape || (key.ctrl && input === "c") || input === "q") {
      exit();
      return;
    }

    // Scroll
    if (key.upArrow) {
      setScrollOffset((o) => Math.max(0, o - 1));
    }
    if (key.downArrow) {
      setScrollOffset((o) => Math.min(results.steps.length - 1, o + 1));
    }

    // Copy report
    if (input === "c") {
      const report = formatMarkdownReport();
      const copied = await copyToClipboard(report);
      setMessage(copied ? "Report copied to clipboard" : "Failed to copy (macOS only)");
      return;
    }

    // Save flow
    if (input === "s") {
      await saveFlow();
      return;
    }
  });

  const visibleSteps = results.steps.slice(scrollOffset, scrollOffset + 10);

  return (
    <Box flexDirection="column" padding={1}>
      {/* Header */}
      <Box marginBottom={1} justifyContent="space-between">
        <Box>
          <Text bold color={PALETTE.brand}>
            {ICONS.diamond} Inspect
          </Text>
          <Text color={PALETTE.subtle}> | </Text>
          <Text color={PALETTE.orange}>{results.agent}</Text>
          <Text color={PALETTE.subtle}> | </Text>
          <Text color={PALETTE.amber}>{results.device}</Text>
        </Box>
        <Box>
          <Text color={PALETTE.muted}>{formatDuration(results.totalDuration)}</Text>
        </Box>
      </Box>

      {/* Result summary */}
      <Box marginBottom={1}>
        <Text color={results.status === "passed" ? PALETTE.green : PALETTE.red} bold>
          {results.status === "passed" ? ICONS.pass : ICONS.fail} {passed}/{total} passed
        </Text>
        {failed > 0 && (
          <>
            <Text color={PALETTE.subtle}> | </Text>
            <Text color={PALETTE.red}>{failed} failed</Text>
          </>
        )}
        <Text color={PALETTE.subtle}> | </Text>
        <Text color={PALETTE.muted}>{results.tokenCount} tokens</Text>
      </Box>

      {/* Instruction */}
      <Box marginBottom={1}>
        <Text color={PALETTE.muted}>"</Text>
        <Text color={PALETTE.text}>{results.instruction}</Text>
        <Text color={PALETTE.muted}>"</Text>
      </Box>

      {/* Steps */}
      <Box flexDirection="column" marginBottom={1}>
        {visibleSteps.map((step, index) => (
          <Box key={index} marginLeft={1}>
            <Box width={3}>
              {step.status === "passed" && <Text color={PALETTE.green}>{ICONS.pass}</Text>}
              {step.status === "failed" && <Text color={PALETTE.red}>{ICONS.fail}</Text>}
              {step.status !== "passed" && step.status !== "failed" && (
                <Text color={PALETTE.subtle}>{ICONS.pending}</Text>
              )}
            </Box>
            <Box flexDirection="column">
              <Text
                color={
                  step.status === "passed"
                    ? PALETTE.green
                    : step.status === "failed"
                      ? PALETTE.red
                      : PALETTE.muted
                }
              >
                {step.instruction}
              </Text>
              {step.summary && <Text color={PALETTE.dim}> Assert: {step.summary}</Text>}
              {step.error && (
                <Text color={PALETTE.red}>
                  {" "}
                  {ICONS.fail} Error: {step.error}
                </Text>
              )}
            </Box>
          </Box>
        ))}
      </Box>

      {/* Message */}
      {message && (
        <Box marginTop={1} marginLeft={2}>
          <Text color={PALETTE.cyan}>{message}</Text>
        </Box>
      )}

      {/* Status bar */}
      <StatusBar
        items={[
          { label: "q", value: "quit" },
          { label: "c", value: "copy report" },
          { label: "s", value: "save flow" },
          ...(results.steps.length > 10 ? [{ label: "↑↓", value: "scroll" }] : []),
        ]}
      />
    </Box>
  );
}
