name: inspect

services:
  inspect:
    build:
      context: ../../
      dockerfile: Dockerfile
    image: ghcr.io/graycodeai/inspect:dev
    env_file:
      - path: ../../.env.example
        required: false
    entrypoint: ["inspect-ci"]
    command: ["--help"]
