// ============================================================================
// CI/CD Integration Agent — CI config generation, quality gates, reporting
// ============================================================================

import type { TestReport } from "./types.js";
import { readFileSync, existsSync, mkdirSync, appendFileSync } from "node:fs";
import { join, dirname } from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface QualityGate {
  metric: string;
  threshold: number;
  operator: ">=" | "<=" | ">" | "<" | "==";
}

export interface GateResult {
  gate: QualityGate;
  actual: number;
  passed: boolean;
}

export interface TrendEntry {
  timestamp: string;
  url: string;
  scores: {
    overall: number;
    a11y: number;
    security: number;
    performance: number;
    seo: number;
  };
}

// ---------------------------------------------------------------------------
// GitHub Actions YAML generation
// ---------------------------------------------------------------------------

export function generateGitHubActionsYAML(options?: {
  schedule?: string;
  branches?: string[];
}): string {
  const branches = options?.branches ?? ["main", "develop"];
  const branchList = branches.map(b => `      - ${b}`).join("\n");

  let onBlock = `on:
  push:
    branches:
${branchList}
  pull_request:
    branches:
${branchList}`;

  if (options?.schedule) {
    onBlock += `\n  schedule:
    - cron: '${options.schedule}'`;
  }

  return `# Generated by Inspect — AI-Powered Browser Testing Platform
name: Inspect Tests

${onBlock}

jobs:
  inspect:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Inspect tests
        run: npx inspect test --url \${{ vars.INSPECT_URL || 'http://localhost:3000' }} --full --json --output .inspect/reports/ci-report.json
        env:
          ANTHROPIC_API_KEY: \${{ secrets.ANTHROPIC_API_KEY }}
          CI: true

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inspect-report
          path: .inspect/reports/
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reportPath = '.inspect/reports/ci-report.json';
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              const score = report.summary.overallScore;
              const passed = report.summary.passed;
              const failed = report.summary.failed;
              const body = \`## Inspect Test Results\\n\\n| Metric | Value |\\n|--------|-------|\\n| Score | \${score}/100 |\\n| Passed | \${passed} |\\n| Failed | \${failed} |\\n\\n[View full report in artifacts]()\`;
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body
              });
            }
`;
}

// ---------------------------------------------------------------------------
// GitLab CI YAML generation
// ---------------------------------------------------------------------------

export function generateGitLabCIYAML(options?: {
  schedule?: string;
  branches?: string[];
}): string {
  const branches = options?.branches ?? ["main", "develop"];
  const branchRefs = branches.map(b => `    - ${b}`).join("\n");

  let scheduleBlock = "";
  if (options?.schedule) {
    scheduleBlock = `
  # Schedule: ${options.schedule}
  # Configure this cron in GitLab CI/CD > Schedules`;
  }

  return `# Generated by Inspect — AI-Powered Browser Testing Platform

stages:
  - test
${scheduleBlock}

inspect:
  stage: test
  image: mcr.microsoft.com/playwright:v1.48.0-jammy
  variables:
    NODE_ENV: test
  before_script:
    - npm ci
  script:
    - npx inspect test --url \${INSPECT_URL:-http://localhost:3000} --full --json --output .inspect/reports/ci-report.json
  artifacts:
    when: always
    paths:
      - .inspect/reports/
    expire_in: 30 days
    reports:
      junit: .inspect/reports/*.xml
  only:
    refs:
${branchRefs}
  tags:
    - docker
`;
}

// ---------------------------------------------------------------------------
// Quality gate evaluation
// ---------------------------------------------------------------------------

export function evaluateQualityGates(
  report: TestReport,
  gates: QualityGate[],
): GateResult[] {
  return gates.map((gate) => {
    const actual = resolveMetric(report, gate.metric);
    const passed = compareValue(actual, gate.threshold, gate.operator);
    return { gate, actual, passed };
  });
}

function resolveMetric(report: TestReport, metric: string): number {
  switch (metric) {
    case "overall":
      return report.summary.overallScore;
    case "a11y": {
      if (report.a11y.length === 0) return 0;
      return Math.round(
        report.a11y.reduce((sum, r) => sum + r.score, 0) / report.a11y.length,
      );
    }
    case "security":
      return report.security?.score ?? 0;
    case "performance": {
      const perf = report.performance;
      if (!perf || perf.length === 0) return 0;
      return Math.round(
        perf.reduce((sum, r) => sum + r.score, 0) / perf.length,
      );
    }
    case "seo":
      return report.seo?.score ?? 0;
    case "responsive":
      return report.responsive?.score ?? 0;
    case "pass_rate": {
      if (report.summary.total === 0) return 0;
      return Math.round(
        (report.summary.passed / report.summary.total) * 100,
      );
    }
    case "failures":
      return report.summary.failed;
    case "duration":
      return report.summary.duration;
    default:
      return 0;
  }
}

function compareValue(
  actual: number,
  threshold: number,
  operator: QualityGate["operator"],
): boolean {
  switch (operator) {
    case ">=":
      return actual >= threshold;
    case "<=":
      return actual <= threshold;
    case ">":
      return actual > threshold;
    case "<":
      return actual < threshold;
    case "==":
      return actual === threshold;
    default:
      return false;
  }
}

// ---------------------------------------------------------------------------
// PR comment generation
// ---------------------------------------------------------------------------

export function generatePRComment(
  report: TestReport,
  previousReport?: TestReport,
): string {
  const score = report.summary.overallScore;
  const statusEmoji = score >= 80 ? "pass" : score >= 50 ? "warn" : "fail";
  const statusLabel =
    statusEmoji === "pass"
      ? "PASSED"
      : statusEmoji === "warn"
        ? "WARNING"
        : "FAILED";

  // Compute category scores
  const a11yScore =
    report.a11y.length > 0
      ? Math.round(
          report.a11y.reduce((s, r) => s + r.score, 0) / report.a11y.length,
        )
      : null;
  const securityScore = report.security?.score ?? null;
  const perfScore =
    report.performance && report.performance.length > 0
      ? Math.round(
          report.performance.reduce((s, r) => s + r.score, 0) /
            report.performance.length,
        )
      : null;
  const seoScore = report.seo?.score ?? null;
  const responsiveScore = report.responsive?.score ?? null;

  // Build score table
  let scoreTable = `| Category | Score |`;
  if (previousReport) {
    scoreTable += ` Delta |`;
  }
  scoreTable += `\n|----------|-------|`;
  if (previousReport) {
    scoreTable += `-------|`;
  }
  scoreTable += "\n";

  const addRow = (label: string, current: number | null, prevReport?: TestReport, metricKey?: string): string => {
    const val = current !== null ? `${current}/100` : "N/A";
    if (previousReport && prevReport && metricKey) {
      const prev = resolveMetric(prevReport, metricKey);
      if (current !== null) {
        const delta = current - prev;
        const deltaStr = delta > 0 ? `+${delta}` : delta < 0 ? `${delta}` : `0`;
        return `| ${label} | ${val} | ${deltaStr} |\n`;
      }
      return `| ${label} | ${val} | - |\n`;
    }
    if (previousReport) {
      return `| ${label} | ${val} | - |\n`;
    }
    return `| ${label} | ${val} |\n`;
  };

  scoreTable += addRow("Overall", score, previousReport, "overall");
  scoreTable += addRow("Accessibility", a11yScore, previousReport, "a11y");
  scoreTable += addRow("Security", securityScore, previousReport, "security");
  scoreTable += addRow("Performance", perfScore, previousReport, "performance");
  scoreTable += addRow("SEO", seoScore, previousReport, "seo");
  scoreTable += addRow("Responsive", responsiveScore, previousReport, "responsive");

  // Summary
  const summary = `**${report.summary.passed}** passed, **${report.summary.failed}** failed, **${report.summary.skipped}** skipped out of **${report.summary.total}** steps (${(report.summary.duration / 1000).toFixed(1)}s)`;

  // Top 5 issues
  const issues: Array<{ severity: string; description: string }> = [];

  for (const a11yReport of report.a11y) {
    for (const issue of a11yReport.issues) {
      issues.push({ severity: issue.severity, description: `[A11y] ${issue.rule}: ${issue.description}` });
    }
  }
  if (report.security) {
    for (const issue of report.security.issues) {
      issues.push({ severity: issue.severity, description: `[Security] ${issue.title}: ${issue.description}` });
    }
  }
  if (report.seo) {
    for (const issue of report.seo.issues) {
      issues.push({ severity: issue.severity, description: `[SEO] ${issue.rule}: ${issue.description}` });
    }
  }

  // Sort by severity
  const severityOrder: Record<string, number> = { critical: 0, serious: 1, high: 1, moderate: 2, medium: 2, minor: 3, low: 4, info: 5 };
  issues.sort((a, b) => (severityOrder[a.severity] ?? 99) - (severityOrder[b.severity] ?? 99));

  let issuesList = "";
  if (issues.length > 0) {
    const topIssues = issues.slice(0, 5);
    issuesList = `\n### Top Issues\n\n`;
    for (const issue of topIssues) {
      issuesList += `- **${issue.severity}**: ${issue.description}\n`;
    }
    if (issues.length > 5) {
      issuesList += `\n_...and ${issues.length - 5} more issues_\n`;
    }
  }

  return `## Inspect Test Results — ${statusLabel}

**Score: ${score}/100** | ${report.url}

### Summary

${summary}

### Scores

${scoreTable}${issuesList}

---
_Generated by [Inspect](https://github.com/nicholasgriffintn/inspect) — AI-Powered Browser Testing Platform_
`;
}

// ---------------------------------------------------------------------------
// Slack payload generation
// ---------------------------------------------------------------------------

export function generateSlackPayload(
  report: TestReport,
  webhookUrl?: string,
): Record<string, unknown> {
  const score = report.summary.overallScore;
  const color = score >= 80 ? "#22c55e" : score >= 50 ? "#eab308" : "#ef4444";
  const statusText = score >= 80 ? "Passed" : score >= 50 ? "Warning" : "Failed";

  const a11yScore =
    report.a11y.length > 0
      ? Math.round(
          report.a11y.reduce((s, r) => s + r.score, 0) / report.a11y.length,
        )
      : null;

  const fields: Array<Record<string, unknown>> = [
    {
      type: "mrkdwn",
      text: `*Overall Score*\n${score}/100`,
    },
    {
      type: "mrkdwn",
      text: `*Tests*\n${report.summary.passed}/${report.summary.total} passed`,
    },
  ];

  if (a11yScore !== null) {
    fields.push({
      type: "mrkdwn",
      text: `*Accessibility*\n${a11yScore}/100`,
    });
  }
  if (report.security) {
    fields.push({
      type: "mrkdwn",
      text: `*Security*\n${report.security.score}/100`,
    });
  }
  if (report.performance && report.performance.length > 0) {
    const avgPerf = Math.round(
      report.performance.reduce((s, r) => s + r.score, 0) /
        report.performance.length,
    );
    fields.push({
      type: "mrkdwn",
      text: `*Performance*\n${avgPerf}/100`,
    });
  }
  if (report.seo) {
    fields.push({
      type: "mrkdwn",
      text: `*SEO*\n${report.seo.score}/100`,
    });
  }

  const blocks: Array<Record<string, unknown>> = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `Inspect: ${statusText} — ${score}/100`,
        emoji: true,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*<${report.url}|${report.title}>*\n${report.summary.passed} passed, ${report.summary.failed} failed, ${report.summary.skipped} skipped | ${(report.summary.duration / 1000).toFixed(1)}s`,
      },
    },
    {
      type: "section",
      fields,
    },
  ];

  // Add failed steps if any
  if (report.summary.failed > 0) {
    const failedSteps = report.results
      .filter((s) => s.status === "fail")
      .slice(0, 5);
    const failedText = failedSteps
      .map((s) => `- ${s.description}${s.error ? `: ${s.error}` : ""}`)
      .join("\n");
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*Failed Steps:*\n${failedText}`,
      },
    });
  }

  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `Inspect — AI-Powered Browser Testing | ${report.timestamp}`,
      },
    ],
  });

  const payload: Record<string, unknown> = {
    blocks,
    attachments: [
      {
        color,
        blocks: [],
      },
    ],
  };

  if (webhookUrl) {
    payload.webhookUrl = webhookUrl;
  }

  return payload;
}

// ---------------------------------------------------------------------------
// Badge SVG generation
// ---------------------------------------------------------------------------

export function generateBadgeSVG(
  label: string,
  score: number,
  thresholds?: { good: number; ok: number },
): string {
  const goodThreshold = thresholds?.good ?? 80;
  const okThreshold = thresholds?.ok ?? 50;

  const color =
    score >= goodThreshold
      ? "#4c1"
      : score >= okThreshold
        ? "#dfb317"
        : "#e05d44";

  const scoreText = `${score}`;
  const labelWidth = label.length * 6.5 + 12;
  const scoreWidth = scoreText.length * 7.5 + 12;
  const totalWidth = labelWidth + scoreWidth;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${totalWidth}" height="20" role="img" aria-label="${escapeXmlAttr(label)}: ${scoreText}">
  <title>${escapeXmlAttr(label)}: ${scoreText}</title>
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <clipPath id="r">
    <rect width="${totalWidth}" height="20" rx="3" fill="#fff"/>
  </clipPath>
  <g clip-path="url(#r)">
    <rect width="${labelWidth}" height="20" fill="#555"/>
    <rect x="${labelWidth}" width="${scoreWidth}" height="20" fill="${color}"/>
    <rect width="${totalWidth}" height="20" fill="url(#s)"/>
  </g>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="11">
    <text aria-hidden="true" x="${labelWidth / 2}" y="15" fill="#010101" fill-opacity=".3">${escapeXmlContent(label)}</text>
    <text x="${labelWidth / 2}" y="14">${escapeXmlContent(label)}</text>
    <text aria-hidden="true" x="${labelWidth + scoreWidth / 2}" y="15" fill="#010101" fill-opacity=".3">${scoreText}</text>
    <text x="${labelWidth + scoreWidth / 2}" y="14">${scoreText}</text>
  </g>
</svg>`;
}

// ---------------------------------------------------------------------------
// Trend tracking
// ---------------------------------------------------------------------------

const DEFAULT_TREND_FILE = join(process.cwd(), ".inspect", "trend.json");

export function saveTrendEntry(
  report: TestReport,
  trendFile?: string,
): void {
  const filePath = trendFile ?? DEFAULT_TREND_FILE;
  const dir = dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const a11yScore =
    report.a11y.length > 0
      ? Math.round(
          report.a11y.reduce((s, r) => s + r.score, 0) / report.a11y.length,
        )
      : 0;

  const perfScore =
    report.performance && report.performance.length > 0
      ? Math.round(
          report.performance.reduce((s, r) => s + r.score, 0) /
            report.performance.length,
        )
      : 0;

  const entry: TrendEntry = {
    timestamp: report.timestamp,
    url: report.url,
    scores: {
      overall: report.summary.overallScore,
      a11y: a11yScore,
      security: report.security?.score ?? 0,
      performance: perfScore,
      seo: report.seo?.score ?? 0,
    },
  };

  const line = JSON.stringify(entry) + "\n";
  appendFileSync(filePath, line, "utf-8");
}

export function loadTrend(trendFile?: string): TrendEntry[] {
  const filePath = trendFile ?? DEFAULT_TREND_FILE;

  if (!existsSync(filePath)) {
    return [];
  }

  const content = readFileSync(filePath, "utf-8");
  const lines = content.split("\n").filter((line) => line.trim().length > 0);
  const entries: TrendEntry[] = [];

  for (const line of lines) {
    try {
      const parsed = JSON.parse(line) as TrendEntry;
      entries.push(parsed);
    } catch {
      // Skip malformed lines
    }
  }

  return entries;
}

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

function escapeXmlAttr(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function escapeXmlContent(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
