// ──────────────────────────────────────────────────────────────────────────────
// Inspect Recorder — Background Service Worker
// Manages recording state and event storage
// ──────────────────────────────────────────────────────────────────────────────

type EventType = "navigation" | "click" | "type" | "select" | "submit" | "scroll";

interface RecordedEvent {
  type: EventType;
  timestamp: number;
  url: string;
  selector?: string;
  text?: string;
  value?: string;
}

interface RecorderState {
  isRecording: boolean;
  events: RecordedEvent[];
  startedAt?: number;
}

/** Get current recording state from storage */
async function getState(): Promise<RecorderState> {
  const result = await chrome.storage.local.get(["recorderState"]);
  return (
    result.recorderState ?? {
      isRecording: false,
      events: [],
    }
  );
}

/** Save recording state to storage */
async function saveState(state: RecorderState): Promise<void> {
  await chrome.storage.local.set({ recorderState: state });
}

/** Start recording */
async function startRecording(): Promise<void> {
  const state = await getState();
  state.isRecording = true;
  state.events = [];
  state.startedAt = Date.now();
  await saveState(state);
  await updateBadge(true);
}

/** Stop recording */
async function stopRecording(): Promise<void> {
  const state = await getState();
  state.isRecording = false;
  await saveState(state);
  await updateBadge(false);
}

/** Add an event to the recording */
async function addEvent(event: RecordedEvent): Promise<void> {
  const state = await getState();
  if (!state.isRecording) return;
  state.events.push(event);
  await saveState(state);
}

/** Get all recorded events */
async function getEvents(): Promise<RecordedEvent[]> {
  const state = await getState();
  return state.events;
}

/** Clear all recorded events */
async function clearEvents(): Promise<void> {
  const state = await getState();
  state.events = [];
  await saveState(state);
}

/** Convert recorded events to Inspect natural-language test script */
function buildTestScript(events: RecordedEvent[]): string {
  const lines: string[] = [];
  let stepNumber = 1;

  for (const event of events) {
    switch (event.type) {
      case "navigation":
        lines.push(`${stepNumber}. Navigate to ${event.url}`);
        break;
      case "click":
        lines.push(`${stepNumber}. Click on ${buildSelectorDesc(event.selector)}`);
        break;
      case "type":
        lines.push(`${stepNumber}. Type "${event.text}" into ${buildSelectorDesc(event.selector)}`);
        break;
      case "select":
        lines.push(
          `${stepNumber}. Select "${event.value}" from ${buildSelectorDesc(event.selector)}`,
        );
        break;
      case "submit":
        lines.push(`${stepNumber}. Submit ${buildSelectorDesc(event.selector)}`);
        break;
      case "scroll":
        lines.push(`${stepNumber}. Scroll the page`);
        break;
    }
    stepNumber++;
  }

  return lines.join("\n");
}

/** Convert CSS selector to human-readable description */
function buildSelectorDesc(selector?: string): string {
  if (!selector) return "the element";

  // Convert common patterns to readable text
  const parts: string[] = [];

  // Extract class names
  const classMatch = selector.match(/\.([\w-]+)/g);
  if (classMatch) {
    parts.push(...classMatch.map((c) => c.slice(1)));
  }

  // Extract ID
  const idMatch = selector.match(/#([\w-]+)/);
  if (idMatch) {
    parts.push(idMatch[1]);
  }

  // Extract tag name
  const tagMatch = selector.match(/^([\w]+)/);
  if (tagMatch) {
    parts.unshift(tagMatch[1]);
  }

  if (parts.length === 0) return "the element";
  return `the ${parts.join(" ")} element`;
}

/** Update extension badge to show recording state */
async function updateBadge(isRecording: boolean): Promise<void> {
  if (isRecording) {
    await chrome.action.setBadgeText({ text: "REC" });
    await chrome.action.setBadgeBackgroundColor({ color: "#ff0000" });
  } else {
    await chrome.action.setBadgeText({ text: "" });
  }
}

/** Generate Inspect test file content from events */
async function exportAsInspectTest(): Promise<string> {
  const events = await getEvents();
  const script = buildTestScript(events);

  return `// Auto-generated by Inspect Recorder
// ${new Date().toISOString()}

/*
 * Natural Language Test Plan:
 *
${script
  .split("\n")
  .map((line) => ` *   ${line}`)
  .join("\n")}
 */

export const testPlan = {
  instruction: "${events
    .filter((e) => e.type === "navigation")
    .map((e) => e.url)
    .join(" → ")}",
  baseUrl: "${events.find((e) => e.type === "navigation")?.url ?? ""}",
  steps: ${JSON.stringify(
    events.map((e, i) => ({
      id: `step-${i + 1}`,
      type: e.type,
      instruction: buildTestScript([e]).replace(/^\d+\.\s*/, ""),
    })),
    null,
    2,
  )},
};
`;
}

// ─── Message Handler ───────────────────────────────────────────────────────

chrome.runtime.onMessage.addListener(
  (
    message: { action: string; event?: RecordedEvent },
    _sender: chrome.runtime.MessageSender,
    sendResponse: (response: {
      success?: boolean;
      events?: RecordedEvent[];
      testScript?: string;
    }) => void,
  ) => {
    switch (message.action) {
      case "startRecording":
        startRecording().then(() => sendResponse({ success: true }));
        return true; // async response
      case "stopRecording":
        stopRecording().then(() => sendResponse({ success: true }));
        return true;
      case "addEvent":
        if (message.event) {
          addEvent(message.event).then(() => sendResponse({ success: true }));
        }
        return true;
      case "getEvents":
        getEvents().then((events) => sendResponse({ events }));
        return true;
      case "clearEvents":
        clearEvents().then(() => sendResponse({ success: true }));
        return true;
      case "getState":
        getState().then((state) => sendResponse({ success: true, events: state.events }));
        return true;
      case "exportTest":
        exportAsInspectTest().then((script) => sendResponse({ testScript: script }));
        return true;
      default:
        sendResponse({});
        return false;
    }
  },
);
