package report

import (
	"fmt"
	"html/template"
	"strings"
	"time"
)

const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Inspect Report — {{.Target}}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f1117; color: #e1e4e8; line-height: 1.6; padding: 2rem; }
.container { max-width: 1200px; margin: 0 auto; }
h1 { font-size: 1.8rem; margin-bottom: 0.5rem; color: #f0f3f6; }
.meta { color: #8b949e; margin-bottom: 2rem; }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 2rem; }
.card { background: #161b22; border: 1px solid #30363d; border-radius: 8px; padding: 1.2rem; text-align: center; }
.card .number { font-size: 2rem; font-weight: 700; }
.card .label { font-size: 0.85rem; color: #8b949e; text-transform: uppercase; }
.card.critical .number { color: #f85149; }
.card.high .number { color: #db6d28; }
.card.medium .number { color: #d29922; }
.card.low .number { color: #58a6ff; }
.card.info .number { color: #8b949e; }
.card.pages .number { color: #3fb950; }
.section { margin-bottom: 2rem; }
.section h2 { font-size: 1.2rem; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 1px solid #30363d; }
.finding { background: #161b22; border: 1px solid #30363d; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; border-left: 4px solid; }
.finding.critical { border-left-color: #f85149; }
.finding.high { border-left-color: #db6d28; }
.finding.medium { border-left-color: #d29922; }
.finding.low { border-left-color: #58a6ff; }
.finding.info { border-left-color: #8b949e; }
.finding .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }
.finding .severity { font-size: 0.75rem; font-weight: 600; text-transform: uppercase; padding: 2px 8px; border-radius: 4px; }
.finding .severity.critical { background: #f8514922; color: #f85149; }
.finding .severity.high { background: #db6d2822; color: #db6d28; }
.finding .severity.medium { background: #d2992222; color: #d29922; }
.finding .severity.low { background: #58a6ff22; color: #58a6ff; }
.finding .severity.info { background: #8b949e22; color: #8b949e; }
.finding .check { font-size: 0.75rem; color: #8b949e; background: #30363d; padding: 2px 6px; border-radius: 3px; }
.finding .message { font-weight: 500; margin-bottom: 0.3rem; }
.finding .url { font-size: 0.85rem; color: #58a6ff; word-break: break-all; }
.finding .fix { font-size: 0.85rem; color: #3fb950; margin-top: 0.3rem; }
.finding .evidence { font-size: 0.8rem; color: #8b949e; font-family: monospace; margin-top: 0.3rem; }
.filters { margin-bottom: 1.5rem; display: flex; gap: 0.5rem; flex-wrap: wrap; }
.filters button { background: #30363d; border: 1px solid #484f58; color: #e1e4e8; padding: 0.4rem 0.8rem; border-radius: 4px; cursor: pointer; font-size: 0.8rem; }
.filters button.active { background: #58a6ff; border-color: #58a6ff; color: #0d1117; }
.footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d; color: #8b949e; font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
<div class="container">
<h1>Inspect Report</h1>
<p class="meta">{{.Target}} — {{.CrawledURLs}} pages crawled in {{.DurationStr}}</p>

<div class="cards">
<div class="card pages"><div class="number">{{.CrawledURLs}}</div><div class="label">Pages</div></div>
<div class="card critical"><div class="number">{{.Critical}}</div><div class="label">Critical</div></div>
<div class="card high"><div class="number">{{.High}}</div><div class="label">High</div></div>
<div class="card medium"><div class="number">{{.Medium}}</div><div class="label">Medium</div></div>
<div class="card low"><div class="number">{{.Low}}</div><div class="label">Low</div></div>
<div class="card info"><div class="number">{{.Info}}</div><div class="label">Info</div></div>
</div>

<div class="section">
<h2>Findings ({{.Total}})</h2>
<div class="filters">
<button class="active" onclick="filterAll()">All</button>
<button onclick="filter('critical')">Critical</button>
<button onclick="filter('high')">High</button>
<button onclick="filter('medium')">Medium</button>
<button onclick="filter('low')">Low</button>
</div>
{{range .Findings}}
<div class="finding {{.SeverityClass}}" data-severity="{{.SeverityClass}}">
<div class="header">
<span class="severity {{.SeverityClass}}">{{.SeverityLabel}}</span>
<span class="check">{{.Check}}</span>
</div>
<div class="message">{{.Message}}</div>
<div class="url">{{.URL}}</div>
{{if .Fix}}<div class="fix">⚡ {{.Fix}}</div>{{end}}
{{if .Evidence}}<div class="evidence">{{.Evidence}}</div>{{end}}
</div>
{{end}}
</div>

<div class="footer">
Generated by <strong>Inspect</strong> by GrayCode AI — {{.GeneratedAt}}
</div>
</div>
<script>
function filter(sev) {
  document.querySelectorAll('.finding').forEach(el => {
    el.style.display = el.dataset.severity === sev ? '' : 'none';
  });
  document.querySelectorAll('.filters button').forEach(b => b.classList.remove('active'));
  event.target.classList.add('active');
}
function filterAll() {
  document.querySelectorAll('.finding').forEach(el => el.style.display = '');
  document.querySelectorAll('.filters button').forEach(b => b.classList.remove('active'));
  event.target.classList.add('active');
}
</script>
</body>
</html>`

type htmlData struct {
	Target      string
	CrawledURLs int
	DurationStr string
	Critical    int
	High        int
	Medium      int
	Low         int
	Info        int
	Total       int
	Findings    []htmlFinding
	GeneratedAt string
}

type htmlFinding struct {
	SeverityClass string
	SeverityLabel string
	Check         string
	Message       string
	URL           string
	Fix           string
	Evidence      string
}

// FormatHTML generates a self-contained HTML report.
func FormatHTML(data ReportData) (string, error) {
	sevCounts := map[string]int{}
	for _, f := range data.Findings {
		sevCounts[f.Severity.String()]++
	}

	htmlFindings := make([]htmlFinding, len(data.Findings))
	for i, f := range data.Findings {
		htmlFindings[i] = htmlFinding{
			SeverityClass: strings.ToLower(f.Severity.String()),
			SeverityLabel: f.Severity.String(),
			Check:         f.Check,
			Message:       f.Message,
			URL:           f.URL,
			Fix:           f.Fix,
			Evidence:      f.Evidence,
		}
	}

	td := htmlData{
		Target:      data.Target,
		CrawledURLs: data.CrawledURLs,
		DurationStr: data.Duration.Round(time.Millisecond).String(),
		Critical:    sevCounts["CRITICAL"],
		High:        sevCounts["HIGH"],
		Medium:      sevCounts["MEDIUM"],
		Low:         sevCounts["LOW"],
		Info:        sevCounts["INFO"],
		Total:       len(data.Findings),
		Findings:    htmlFindings,
		GeneratedAt: time.Now().Format("2006-01-02 15:04:05"),
	}

	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, td); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}

	return buf.String(), nil
}
