package report

import (
	"strings"
	"testing"
	"time"
)

func TestFormatMarkdown_WithFindings(t *testing.T) {
	data := ReportData{
		Target:      "https://example.com",
		CrawledURLs: 8,
		Duration:    2 * time.Second,
		Findings: []Finding{
			{
				Check:    "security",
				Severity: SeverityCritical,
				URL:      "https://example.com",
				Message:  "Exposed secret",
				Fix:      "Remove secret from source",
				Evidence: "api_key=abc123",
			},
			{
				Check:    "links",
				Severity: SeverityHigh,
				URL:      "https://example.com/broken",
				Message:  "404 Not Found",
				Element:  `<a href="/missing">`,
			},
			{
				Check:    "a11y",
				Severity: SeverityMedium,
				URL:      "https://example.com",
				Message:  "Missing alt text",
			},
			{
				Check:    "perf",
				Severity: SeverityLow,
				URL:      "https://example.com",
				Message:  "Large page size",
			},
			{
				Check:    "seo",
				Severity: SeverityInfo,
				URL:      "https://example.com",
				Message:  "Missing canonical link",
			},
		},
	}
	data.Stats.ByCheck = map[string]int{
		"security": 1,
		"links":    1,
		"a11y":     1,
		"perf":     1,
		"seo":      1,
	}

	output := FormatMarkdown(data)

	if output == "" {
		t.Fatal("expected non-empty output")
	}

	// Check heading
	if !strings.Contains(output, "# Inspect Report: https://example.com") {
		t.Error("expected report heading with target")
	}

	// Check crawl stats
	if !strings.Contains(output, "**8** pages") {
		t.Error("expected crawled pages count")
	}

	// Check summary table
	if !strings.Contains(output, "| Severity | Count |") {
		t.Error("expected severity summary table")
	}
	if !strings.Contains(output, "CRITICAL") {
		t.Error("expected CRITICAL in severity table")
	}
	if !strings.Contains(output, "HIGH") {
		t.Error("expected HIGH in severity table")
	}

	// Check total count
	if !strings.Contains(output, "**Total: 5 findings**") {
		t.Error("expected total findings count")
	}

	// Check findings content
	if !strings.Contains(output, "**[security]** Exposed secret") {
		t.Error("expected security finding")
	}
	if !strings.Contains(output, "- URL: `https://example.com`") {
		t.Error("expected URL in finding detail")
	}
	if !strings.Contains(output, "- Fix: Remove secret from source") {
		t.Error("expected fix in finding detail")
	}
	if !strings.Contains(output, "- Evidence: `api_key=abc123`") {
		t.Error("expected evidence in finding detail")
	}
	if !strings.Contains(output, "- Element: `<a href=\"/missing\">`") {
		t.Error("expected element in finding detail")
	}

	// Check by-check breakdown
	if !strings.Contains(output, "### By Check") {
		t.Error("expected by-check breakdown")
	}

	// Check footer
	if !strings.Contains(output, "Generated by [Inspect]") {
		t.Error("expected generated footer")
	}
}

func TestFormatMarkdown_NoFindings(t *testing.T) {
	data := ReportData{
		Target:      "https://clean.example.com",
		CrawledURLs: 3,
		Duration:    1 * time.Second,
	}

	output := FormatMarkdown(data)

	if !strings.Contains(output, "# Inspect Report: https://clean.example.com") {
		t.Error("expected report heading")
	}
	if !strings.Contains(output, "**No issues found.**") {
		t.Error("expected 'No issues found' message")
	}
	// Should not have findings section
	if strings.Contains(output, "## Findings") {
		t.Error("should not have findings section when empty")
	}
}

func TestFormatMarkdown_SeverityOrder(t *testing.T) {
	data := ReportData{
		Target:      "https://example.com",
		CrawledURLs: 1,
		Duration:    100 * time.Millisecond,
		Findings: []Finding{
			{Check: "seo", Severity: SeverityInfo, URL: "https://example.com", Message: "info issue"},
			{Check: "security", Severity: SeverityCritical, URL: "https://example.com", Message: "critical issue"},
			{Check: "links", Severity: SeverityLow, URL: "https://example.com", Message: "low issue"},
		},
	}

	output := FormatMarkdown(data)

	// CRITICAL should appear before LOW, and LOW before INFO
	critIdx := strings.Index(output, "CRITICAL")
	lowIdx := strings.Index(output, "### LOW")
	infoIdx := strings.Index(output, "### INFO")

	if critIdx == -1 || lowIdx == -1 || infoIdx == -1 {
		t.Fatal("expected all severity sections to be present")
	}
	if critIdx > lowIdx {
		t.Error("CRITICAL should appear before LOW")
	}
	if lowIdx > infoIdx {
		t.Error("LOW should appear before INFO")
	}
}

func TestFormatMarkdown_NoByCheckSection(t *testing.T) {
	data := ReportData{
		Target:      "https://example.com",
		CrawledURLs: 1,
		Duration:    100 * time.Millisecond,
		Findings: []Finding{
			{Check: "links", Severity: SeverityHigh, URL: "https://example.com", Message: "broken link"},
		},
	}
	// Stats.ByCheck is nil — should skip "By Check" section

	output := FormatMarkdown(data)
	if strings.Contains(output, "### By Check") {
		t.Error("should not have By Check section when stats are nil")
	}
}

func TestSeverityEmoji(t *testing.T) {
	tests := []struct {
		sev      Severity
		expected string
	}{
		{SeverityCritical, "CRITICAL"},
		{SeverityHigh, "HIGH"},
		{SeverityMedium, "MEDIUM"},
		{SeverityLow, "LOW"},
		{SeverityInfo, "INFO"},
		{Severity(99), "UNKNOWN"},
	}

	for _, tt := range tests {
		got := severityEmoji(tt.sev)
		if got != tt.expected {
			t.Errorf("severityEmoji(%d) = %q, want %q", tt.sev, got, tt.expected)
		}
	}
}
