package report

import (
	"fmt"
	"strings"
	"time"
)

// FormatMarkdown renders the report as a Markdown document suitable for
// GitHub PR comments or issue bodies.
func FormatMarkdown(data ReportData) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Inspect Report: %s\n\n", data.Target))
	b.WriteString(fmt.Sprintf("Crawled **%d** pages in **%s**\n\n", data.CrawledURLs, data.Duration.Round(time.Millisecond)))

	if len(data.Findings) == 0 {
		b.WriteString("**No issues found.**\n")
		return b.String()
	}

	// Summary table
	sevCounts := map[Severity]int{}
	for _, f := range data.Findings {
		sevCounts[f.Severity]++
	}

	b.WriteString("## Summary\n\n")
	b.WriteString("| Severity | Count |\n")
	b.WriteString("|----------|-------|\n")
	order := []Severity{SeverityCritical, SeverityHigh, SeverityMedium, SeverityLow, SeverityInfo}
	for _, sev := range order {
		count := sevCounts[sev]
		if count > 0 {
			b.WriteString(fmt.Sprintf("| %s | %d |\n", severityEmoji(sev), count))
		}
	}
	b.WriteString(fmt.Sprintf("\n**Total: %d findings**\n\n", len(data.Findings)))

	// Check breakdown
	if data.Stats.ByCheck != nil && len(data.Stats.ByCheck) > 0 {
		b.WriteString("### By Check\n\n")
		b.WriteString("| Check | Findings |\n")
		b.WriteString("|-------|----------|\n")
		for check, count := range data.Stats.ByCheck {
			b.WriteString(fmt.Sprintf("| %s | %d |\n", check, count))
		}
		b.WriteString("\n")
	}

	// Findings grouped by severity
	b.WriteString("## Findings\n\n")

	grouped := map[Severity][]Finding{}
	for _, f := range data.Findings {
		grouped[f.Severity] = append(grouped[f.Severity], f)
	}

	for _, sev := range order {
		items := grouped[sev]
		if len(items) == 0 {
			continue
		}
		b.WriteString(fmt.Sprintf("### %s (%d)\n\n", severityEmoji(sev), len(items)))

		for _, f := range items {
			b.WriteString(fmt.Sprintf("- **[%s]** %s\n", f.Check, f.Message))
			b.WriteString(fmt.Sprintf("  - URL: `%s`\n", f.URL))
			if f.Element != "" {
				b.WriteString(fmt.Sprintf("  - Element: `%s`\n", f.Element))
			}
			if f.Fix != "" {
				b.WriteString(fmt.Sprintf("  - Fix: %s\n", f.Fix))
			}
			if f.Evidence != "" {
				b.WriteString(fmt.Sprintf("  - Evidence: `%s`\n", f.Evidence))
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("*Generated by [Inspect](https://github.com/GrayCodeAI/inspect)*\n")

	return b.String()
}

func severityEmoji(sev Severity) string {
	switch sev {
	case SeverityCritical:
		return "CRITICAL"
	case SeverityHigh:
		return "HIGH"
	case SeverityMedium:
		return "MEDIUM"
	case SeverityLow:
		return "LOW"
	case SeverityInfo:
		return "INFO"
	default:
		return "UNKNOWN"
	}
}
