// @inspect/core — Backward-compatibility facade
// Re-exports from @inspect/orchestrator, @inspect/git, @inspect/devices
// New code should import the specific packages directly.

export {
  TestExecutor,
  TestScheduler,
  RecoveryManager,
  SpeculativePlanner,
  CheckpointManager,
  DashboardOrchestrator,
  AGENT_TOOLS,
  VISUAL_TOOLS,
  NON_VISUAL_TOOLS,
  CACHEABLE_TOOLS,
  SYSTEM_PROMPT,
  RunCache,
  ErrorClassifier,
  PluginLoader,
  definePlugin,
  DiffRunner,
  DiffPlanGenerator,
  AdversarialExecutor,
  RetryExecutor,
  RETRY_PRESETS,
  TagExpression,
  TestFilter,
  BenchmarkTracker,
  TestPrioritizer,
  CrossBrowserComparator,
  TestGenerator,
  FlakinessDetector,
  WatchEngine,
  TestCoverageAnalyzer,
  detectFramework,
  VisualRegression,
  generatePlaywrightTest,
  exportPlaywrightTest,
  generatePlaywrightFromSuite,
  exportPlaywrightFromSuite,
  type ExecutionConfig,
  type ExecutionResult,
  type ExecutionProgress,
  type ExecutorDependencies,
  type StepPlan,
  type StepResult,
  type AdversarialFinding,
  type SchedulerConfig,
  type ScheduledRun,
  type FailureType,
  type RecoveryStrategy,
  type DiagnosisResult,
  type RecoveryExecutors,
  type SpeculativePlan,
  type SpeculativeStats,
  type CheckpointData,
  type CheckpointStep,
  type CachedTestRun,
  type CachedStep,
  type RunCacheConfig,
  type ErrorCategory,
  type ClassifiedError,
  type InspectPlugin,
  type PluginContext,
  type PluginTool,
  type PluginAssertion,
  type DiffTestConfig,
  type CoverageMapEntry,
  type DiffAnalysis,
  type ChangeCategory,
  type DiffPlanGeneratorConfig,
  type AdversarialConfig,
  type RetryPolicy,
  type RetryStrategy,
  type RetryResult,
  type RetryAttempt,
  type TaggedTest,
  type BenchmarkEntry,
  type BenchmarkTrend,
  type BenchmarkReport,
  type TestEntry,
  type PrioritizationInput,
  type PrioritizationWeights,
  type PrioritizedTest,
  type PrioritizationResult,
  type CrossBrowserConfig,
  type BrowserRunResult,
  type CrossBrowserDiff,
  type StepDiff,
  type PerformanceComparison,
  type PageAnalysis,
  type GeneratedTest,
  type GeneratedTestSuite,
  type GeneratedStep,
  type TestCategory,
  type PageType,
  type TestExecution,
  type FlakinessScore,
  type FlakinessReport,
  type WatchEngineOptions,
  type WatchRunResult,
  type WatchState,
  type WatchEvent,
  type CoverageReport,
  type ImportNode,
  type DetectedFramework,
  type VisualRegressionConfig,
  type VisualComparisonResult,
  type VisualRegressionReport,
  type PlaywrightExportOptions,
  type AnalyzedElement,
  type FormInfo,
  SelfHealer,
  HealingStrategy,
  DOMDiffer,
  type HealingAttemptResult,
  type DOMChange,
  type DOMDiffResult,
  mapMethodToStrategy,
  StaticAnalyzer,
  type RouteInfo,
  type ApiCallInfo,
  type EventHandlerInfo,
  type StaticAnalysisResult,
  SyncSpeculativePlanner,
} from "@inspect/orchestrator";

export {
  GitManager,
  Fingerprint,
  ContextBuilder,
  GitHubPR,
  PRComments,
  type GitContext,
  type ContextLimits,
  type PRInfo,
  type PRDiff,
  type CommentPayload,
  type StatusPayload,
} from "@inspect/git";

export {
  DevicePresets,
  getPreset,
  listPresets,
  resolveDevices,
  getPresetsByCategory,
  DevicePool,
  type DeviceConfig,
  type DeviceRunResult,
} from "@inspect/devices";
