// @inspect/quality — Backward-compatibility facade
// Re-exports from @inspect/a11y, @inspect/lighthouse-quality, @inspect/chaos,
// @inspect/security-scanner, @inspect/mocking, @inspect/resilience
// New code should import the specific packages directly.

export {
  AccessibilityAuditor,
  A11Y_RULES,
  ALL_A11Y_RULES,
  getRulesByTag,
  getRulesByImpact,
  getRulesByCategory,
  getRuleById,
  SitemapAuditor,
  type A11yAuditOptions,
  type A11yRuleDefinition,
  type SitemapAuditOptions,
  type SitemapAuditResult,
} from "@inspect/a11y";

export {
  LighthouseAuditor,
  BudgetManager,
  BUDGET_PRESETS,
  ScoreHistory,
  type LighthouseOptions,
  type LighthouseBudget,
  type BudgetThreshold,
  type BudgetAssertionResult,
  type BudgetCheckResult,
  type ScoreEntry,
  type ScoreTrend,
} from "@inspect/lighthouse-quality";

export {
  ChaosEngine,
  ClickerGremlin,
  TyperGremlin,
  ScrollerGremlin,
  FormFillerGremlin,
  ToucherGremlin,
  GREMLIN_REGISTRY,
  createGremlin,
  FPS_MONITOR_SCRIPT,
  FPS_MONITOR_STOP_SCRIPT,
  ERROR_MONITOR_SCRIPT,
  ERROR_MONITOR_RESULTS_SCRIPT,
  ALERT_MONITOR_SCRIPT,
  type ChaosOptions,
  type Gremlin,
  type GremlinInjectionOptions,
  type FPSMonitorResult,
  type ErrorMonitorResult,
  type AlertMonitorResult,
} from "@inspect/chaos";

export {
  NucleiScanner,
  ZAPScanner,
  SecurityProxy,
  type NucleiOptions,
  type ZAPOptions,
  type SecurityProxyConfig,
  type SecurityHeaderFinding,
  type TrafficLogEntry,
} from "@inspect/security-scanner";

export {
  NetworkInterceptor,
  rest,
  graphql,
  response,
  HttpResponse,
  delay,
  passthrough,
  isPassthrough,
  matchUrl,
  parseQuery,
  parseGraphQLOperation,
  MockGenerator,
  FakeData,
  ws,
  WsMockBuilder,
  WsHandlerBuilder,
  WsMessageMatcher,
  MockWsConnection,
  WsRecorder,
  type InterceptorOptions,
  type InterceptedRequest,
  type MockHandler,
  type MockRequest,
  type MockResponse,
  type HandlerFn,
  type WsMessageHandlerFn,
} from "@inspect/mocking";

export {
  FaultInjector,
  LatencyToxic,
  BandwidthToxic,
  TimeoutToxic,
  DisconnectToxic,
  SlowCloseToxic,
  SlicerToxic,
  LimitDataToxic,
  createToxic,
  TOXIC_PRESETS,
  ProxyServer,
  TOXICITY_PRESETS,
  type FaultConfig,
  type FaultStats,
  type Toxic,
} from "@inspect/resilience";
