import { describe, it, expect } from "vitest";
import { MarkdownReporter } from "./markdown.js";
import type { SuiteResult } from "./markdown.js";

function makeSuite(overrides?: Partial<SuiteResult>): SuiteResult {
  return {
    name: "Test Suite",
    startedAt: 1700000000000,
    finishedAt: 1700000005000,
    tests: [
      {
        name: "Login test",
        status: "passed",
        duration: 2500,
        startedAt: 1700000000000,
        finishedAt: 1700000002500,
        steps: [
          { index: 1, action: "click", target: "#login", status: "passed", duration: 500 },
          {
            index: 2,
            action: "fill",
            target: "#email",
            value: "user@test.com",
            status: "passed",
            duration: 300,
          },
        ],
        screenshots: [{ name: "login-page", path: "/tmp/login.png", timestamp: 1700000001000 }],
      },
      {
        name: "Submit form",
        status: "failed",
        duration: 1500,
        startedAt: 1700000002500,
        finishedAt: 1700000004000,
        steps: [
          {
            index: 1,
            action: "click",
            target: "#submit",
            status: "failed",
            duration: 1500,
            error: "Element not found",
          },
        ],
        error: { message: "Element #submit not found" },
        screenshots: [],
      },
      {
        name: "Skipped test",
        status: "skipped",
        duration: 0,
        startedAt: 1700000004000,
        finishedAt: 1700000004000,
        steps: [],
        screenshots: [],
      },
    ],
    environment: { browser: "chromium", url: "https://example.com", model: "claude" },
    ...overrides,
  };
}

describe("MarkdownReporter", () => {
  const reporter = new MarkdownReporter();

  describe("generate", () => {
    it("produces a full markdown report", () => {
      const report = reporter.generate(makeSuite());
      expect(report).toContain("# Inspect Test Report");
      expect(report).toContain("**Suite:** Test Suite");
      expect(report).toContain("## Summary");
      expect(report).toContain("| Total Tests | 3 |");
      expect(report).toContain("| Passed | 1 |");
      expect(report).toContain("| Failed | 1 |");
      expect(report).toContain("| Skipped | 1 |");
    });

    it("shows failed tests before passed tests", () => {
      const report = reporter.generate(makeSuite());
      const failedIdx = report.indexOf("## Failed Tests");
      const passedIdx = report.indexOf("## Passed Tests");
      expect(failedIdx).toBeLessThan(passedIdx);
    });

    it("includes environment info", () => {
      const report = reporter.generate(makeSuite());
      expect(report).toContain("## Environment");
      expect(report).toContain("**Browser:** chromium");
      expect(report).toContain("**URL:** https://example.com");
    });

    it("includes error details for failed tests", () => {
      const report = reporter.generate(makeSuite());
      expect(report).toContain("Element #submit not found");
    });

    it("includes step tables", () => {
      const report = reporter.generate(makeSuite());
      expect(report).toContain("| # | Action | Target | Status | Duration |");
      expect(report).toContain("| 1 | click |");
    });

    it("lists skipped tests", () => {
      const report = reporter.generate(makeSuite());
      expect(report).toContain("## Skipped Tests");
      expect(report).toContain("- Skipped test");
    });

    it("includes footer with duration", () => {
      const report = reporter.generate(makeSuite());
      expect(report).toContain("Generated by Inspect");
      expect(report).toContain("5.0s");
    });
  });

  describe("generateCompact", () => {
    it("shows FAIL when tests fail", () => {
      const compact = reporter.generateCompact(makeSuite());
      expect(compact).toContain("**FAIL**");
      expect(compact).toContain("1/3 passed");
    });

    it("shows PASS when all pass", () => {
      const suite = makeSuite({
        tests: [
          {
            name: "OK test",
            status: "passed",
            duration: 100,
            startedAt: 1700000000000,
            finishedAt: 1700000000100,
            steps: [],
            screenshots: [],
          },
        ],
      });
      const compact = reporter.generateCompact(suite);
      expect(compact).toContain("**PASS**");
    });

    it("lists failed test names", () => {
      const compact = reporter.generateCompact(makeSuite());
      expect(compact).toContain("Submit form");
    });
  });
});
