// ============================================================================
// @inspect/browser - File Upload Testing
//
// Detects file upload inputs and tests them with generated test files.
// Supports various file types and sizes.
// Inspired by Skyvern's UploadFileAction.
// ============================================================================

import type { Page } from "playwright";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

export interface FileUploadResult {
  selector: string;
  fileName: string;
  fileType: string;
  fileSize: number;
  success: boolean;
  error?: string;
}

/**
 * FileUploadTester detects and tests file upload inputs.
 */
export class FileUploadTester {
  /**
   * Detect all file upload inputs on the page.
   */
  async detectInputs(page: Page): Promise<string[]> {
    return page.evaluate(() => {
      const inputs = document.querySelectorAll('input[type="file"]');
      return Array.from(inputs).map((el) => {
        const id = el.id ? `#${el.id}` : "";
        const name = el.getAttribute("name") ? `[name="${el.getAttribute("name")}"]` : "";
        return `input[type="file"]${id}${name}` || "input[type=file]";
      });
    });
  }

  /**
   * Test file upload with a generated test file.
   */
  async testUpload(
    page: Page,
    selector: string,
    fileType: "text" | "image" | "pdf" | "csv" = "text",
  ): Promise<FileUploadResult> {
    const file = this.generateTestFile(fileType);

    try {
      const input = page.locator(selector).first();
      await input.setInputFiles(file.path);

      return {
        selector,
        fileName: file.name,
        fileType: file.type,
        fileSize: file.size,
        success: true,
      };
    } catch (err) {
      return {
        selector,
        fileName: file.name,
        fileType: file.type,
        fileSize: file.size,
        success: false,
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  /**
   * Test upload with oversized file (boundary testing).
   */
  async testOversizedUpload(page: Page, selector: string, sizeKB = 10240): Promise<FileUploadResult> {
    const dir = join(tmpdir(), "inspect-test-files");
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

    const path = join(dir, "oversized-test.bin");
    writeFileSync(path, Buffer.alloc(sizeKB * 1024, 0));

    try {
      const input = page.locator(selector).first();
      await input.setInputFiles(path);

      return {
        selector,
        fileName: "oversized-test.bin",
        fileType: "application/octet-stream",
        fileSize: sizeKB * 1024,
        success: true,
      };
    } catch (err) {
      return {
        selector,
        fileName: "oversized-test.bin",
        fileType: "application/octet-stream",
        fileSize: sizeKB * 1024,
        success: false,
        error: err instanceof Error ? err.message : String(err),
      };
    }
  }

  private generateTestFile(type: string): { path: string; name: string; type: string; size: number } {
    const dir = join(tmpdir(), "inspect-test-files");
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

    switch (type) {
      case "image": {
        // 1x1 red PNG
        const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/5+hHgAHggJ/PchI7wAAAABJRU5ErkJggg==", "base64");
        const path = join(dir, "test-image.png");
        writeFileSync(path, png);
        return { path, name: "test-image.png", type: "image/png", size: png.length };
      }
      case "csv": {
        const csv = "Name,Email,Age\nJohn,john@test.com,30\nJane,jane@test.com,25\n";
        const path = join(dir, "test-data.csv");
        writeFileSync(path, csv);
        return { path, name: "test-data.csv", type: "text/csv", size: csv.length };
      }
      case "pdf": {
        // Minimal valid PDF
        const pdf = "%PDF-1.0\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj 2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj 3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R>>endobj\nxref\n0 4\n0000000000 65535 f \n0000000009 00000 n \n0000000058 00000 n \n0000000115 00000 n \ntrailer<</Size 4/Root 1 0 R>>\nstartxref\n190\n%%EOF";
        const path = join(dir, "test-document.pdf");
        writeFileSync(path, pdf);
        return { path, name: "test-document.pdf", type: "application/pdf", size: pdf.length };
      }
      default: {
        const text = "This is a test file generated by Inspect for upload testing.\nTimestamp: " + new Date().toISOString();
        const path = join(dir, "test-file.txt");
        writeFileSync(path, text);
        return { path, name: "test-file.txt", type: "text/plain", size: text.length };
      }
    }
  }
}
